# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1Player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team1Player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team1Player3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team1Player4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team1Player5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Player3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Player4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2Player5',
            field=models.IntegerField(default=0),
        ),
    ]
