# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0002_auto_20151230_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='matchID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='Creeps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='MinutesPlayed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
