# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0005_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.IntegerField(default=0),
        ),
    ]
