# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0007_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='L0game1',
            new_name='L0game1t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0game2',
            new_name='L0game1t2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0game3',
            new_name='L0game2t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game1',
            new_name='L0game2t2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game2',
            new_name='L0game3t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game3',
            new_name='L0game3t2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game1',
            new_name='L1game1t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game2',
            new_name='L1game1t2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game3',
            new_name='L1game2t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game1',
            new_name='L1game2t2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game2',
            new_name='L1game3t1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game3',
            new_name='L1game3t2',
        ),
        migrations.AddField(
            model_name='week',
            name='L2game1t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game1t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game2t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game2t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game3t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game3t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game1t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game1t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game2t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game2t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game3t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game3t2',
            field=models.IntegerField(default=0),
        ),
    ]
