# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0010_auto_20160106_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='L0game1time',
            new_name='L0game1date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0game2time',
            new_name='L0game2date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0game3time',
            new_name='L0game3date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game1time',
            new_name='L1game1date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game2time',
            new_name='L1game2date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1game3time',
            new_name='L1game3date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game1time',
            new_name='L2game1date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game2time',
            new_name='L2game2date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2game3time',
            new_name='L2game3date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game1time',
            new_name='L3game1date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game2time',
            new_name='L3game2date',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3game3time',
            new_name='L3game3date',
        ),
    ]
