# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0011_auto_20160108_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='L0game1Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L0game2Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L0game3Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L1game1Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L1game2Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L1game3Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game1Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game2Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L2game3Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game1Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game2Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
        migrations.AddField(
            model_name='week',
            name='L3game3Time',
            field=models.TimeField(default=datetime.time(16, 20)),
        ),
    ]
