# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0013_auto_20160114_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourneyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.IntegerField(default=0)),
                ('team2', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=50)),
                ('week', models.IntegerField(default=0)),
                ('league', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('rift', models.IntegerField(default=0)),
            ],
        ),
    ]
