# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0014_tourneycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='DamageDealt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
