# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0015_stats_damagedealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='DamageReceived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='DoubleKills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='PentaKills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='QuadraKills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='TeamKillTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='TripleKills',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
