# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0012_auto_20160108_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='L0game1Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L0game1date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L0game2Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L0game2date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L0game3Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L0game3date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game1Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game1date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game2Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game2date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game3Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L1game3date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game1Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game1date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game2Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game2date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game3Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L2game3date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game1Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game1date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game2Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game2date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game3Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 20)),
        ),
        migrations.AlterField(
            model_name='week',
            name='L3game3date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
