# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0015_auto_20160114_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='L0game1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0game1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0game2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0game2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0game3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0game3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1game3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2game3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3game3Game2',
        ),
    ]
