# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0020_auto_20160114_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='L0match1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0match1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0match2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0match2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0match3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L0match3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L1match3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L2match3Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match1Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match1Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match2Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match2Game2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match3Game1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='L3match3Game2',
        ),
    ]
