# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0022_auto_20160114_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='L0match1Game1',
            new_name='L0game1Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0match1Game2',
            new_name='L0game1Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0match2Game1',
            new_name='L0game2Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0match2Game2',
            new_name='L0game2Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0match3Game1',
            new_name='L0game3Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L0match3Game2',
            new_name='L0game3Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match1Game1',
            new_name='L1game1Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match1Game2',
            new_name='L1game1Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match2Game1',
            new_name='L1game2Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match2Game2',
            new_name='L1game2Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match3Game1',
            new_name='L1game3Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L1match3Game2',
            new_name='L1game3Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match1Game1',
            new_name='L2game1Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match1Game2',
            new_name='L2game1Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match2Game1',
            new_name='L2game2Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match2Game2',
            new_name='L2game2Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match3Game1',
            new_name='L2game3Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L2match3Game2',
            new_name='L2game3Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match1Game1',
            new_name='L3game1Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match1Game2',
            new_name='L3game1Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match2Game1',
            new_name='L3game2Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match2Game2',
            new_name='L3game2Game2',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match3Game1',
            new_name='L3game3Game1',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='L3match3Game2',
            new_name='L3game3Game2',
        ),
    ]
