# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0002_auto_20151225_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='PlayerID',
            new_name='SummonerID',
        ),
    ]
