# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0003_auto_20151225_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='SummonerID',
        ),
        migrations.AddField(
            model_name='player',
            name='SummonerNumber',
            field=models.IntegerField(default=0),
        ),
    ]
