# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0004_auto_20151225_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='CaptainID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Player1ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Player2ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Player3ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Player4ID',
            field=models.IntegerField(default=0),
        ),
    ]
