# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsrunner', '0005_auto_20151225_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LargestCrit', models.IntegerField(default=0)),
                ('LargestCritPlayerNum', models.IntegerField(default=0)),
                ('LasrgetCritGameNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Assists',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Deaths',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='GamesPlayed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='GoldTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Kills',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
